#!/bin/sh

KIKI_DIR="/tmp/kiki"
mkdir -p $KIKI_DIR
KIKI_OUT_FILE=`mktemp $KIKI_DIR/find-XXXXX`

kiki "--prefix=$1" "(f || true)" "cat > $KIKI_OUT_FILE"
if [ -s $KIKI_OUT_FILE ]
then
    $XARGS -a $KIKI_OUT_FILE echo -n | copy
fi
