#!/bin/sh

KIKI_DIR="/tmp/kiki"
mkdir -p $KIKI_DIR
KIKI_OUT_FILE=`mktemp $KIKI_DIR/grep-XXXXX`

kiki "cat $1" "cat > $KIKI_OUT_FILE"
if [ -s $KIKI_OUT_FILE ]
then
    gxargs -a $KIKI_OUT_FILE echo -n | pbcopy
fi
